#' @title Reading, Processing and Visualizing Astrophysical N-Body Simulation Data
#'
#' @description Routines for post-processing and visualizing astrophysical N-body+SPH simulation data, written to deal with data generated by the Gadget code at <https://wwwmpa.mpa-garching.mpg.de/gadget4/>. The routines are most suitable for smaller simulations (up to ~1e8 particles), as they have been written assuming that the simulation particles of individual snapshots can be loaded into RAM memory at once.
#'
#' @author Danail Obreschkow
#'
#' @docType package
#' @name gadgetry
NULL
